name: Build Blog example

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    permissions:
      contents: read
      packages: write
      
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.3.1
          
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
          
      - name: Install dependencies
        run: pnpm install
        
      - name: Build blog example
        run: pnpm build:blog-example
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
